### ISSUE TITLE
Optimize binary file size

### ISSUE THREAD

**Issue by ImranSaadi** [warnerbros/cpe-manifest-ios-data#1]
The data binding library significantly increases binary file size once linked to target.

**Comment by alecananian** [comment]
We've determined that the data binding library did not increase binary file size by a significant amount.  With release [v3.0.0](https://github.com/warnerbros/cpe-manifest-ios-data/releases/tag/3.0.0), the library now only contains a subset of the data binding that it did before, lowering the number of files in the library and greatly improving build and archive times.
